version: '3.7'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456     
    volumes:
      - data:/var/lib/mysql
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: djangoapp
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env   

volumes:
  data: